<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NTJVOKJ" failures="5" tests="7" name="Runner_Files.Help_positive_scenarios_runner" time="50.446" errors="0" timestamp="2021-06-28T14:25:39 IST" skipped="0">
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.438">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.help_positive_tc_004(Help_positive_scenarios.java:93)
at ✽.check able to see description , when user click on Referral title(file:///C:/Users/Admin/Downloads/demo-main/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.396">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.help_positive_tc_006(Help_positive_scenarios.java:130)
at ✽.check able to see description , when user click on Payments  title(file:///C:/Users/Admin/Downloads/demo-main/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.446">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.help_positive_tc_003(Help_positive_scenarios.java:75)
at ✽.check able to see description , when user click on Award Points title(file:///C:/Users/Admin/Downloads/demo-main/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.412">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.help_positive_tc_005(Help_positive_scenarios.java:111)
at ✽.check able to see description , when user click on Profile title(file:///C:/Users/Admin/Downloads/demo-main/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="1.614"/>
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.361">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.help_positive_tc_007(Help_positive_scenarios.java:148)
at ✽.check able to see description , when user click on Add coverage  title(file:///C:/Users/Admin/Downloads/demo-main/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="46.779"/>
  <system-out/>
</testsuite> <!-- Runner_Files.Help_positive_scenarios_runner -->
